"""Generate TeX files from `.impe` YAML documents."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .fonts import load_registry, repo_root
from .schema import load_impe


AUTO_HEADER = "% Auto-generated by IMPE. Do not edit manually.\n"
LATEX_SPECIALS = {
    "\\": r"\textbackslash{}",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "&": r"\&",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def generate_tex(impe_path: Path, output_dir: Path | None = None) -> Path:
    data, warnings = load_impe(impe_path)
    build = data.get("build", {})
    if output_dir is None:
        output_dir = impe_path.parent / build.get("out_dir", "build")
    output_dir.mkdir(parents=True, exist_ok=True)

    fonts_path = output_dir / "generated-fonts.tex"
    content_path = output_dir / "generated-content.tex"
    main_path = output_dir / "main.tex"
    warnings_path = output_dir / "generation-warnings.log"

    fonts_path.write_text(_generate_fonts(data, output_dir), encoding="utf-8")
    content_path.write_text(_generate_content(data), encoding="utf-8")
    main_path.write_text(_generate_main(data), encoding="utf-8")

    if warnings:
        warnings_path.write_text("\n".join(warnings) + "\n", encoding="utf-8")
    elif warnings_path.exists():
        warnings_path.unlink()

    return main_path


def _generate_main(data: dict[str, Any]) -> str:
    document = data["document"]
    template = data["template"]
    class_name = _tex_identifier(document.get("class", "nextreport"), "nextreport")
    title = escape_latex(str(document.get("title", "Untitled Document")))
    subtitle = escape_latex(str(document.get("subtitle", "")))
    author = escape_latex(str(document.get("author", "")))
    layout = _tex_atom(template.get("layout", "report"))
    globalfonts = _tex_list(template.get("globalfonts", []))
    fonts = _tex_list(template.get("fonts", []))
    features = _tex_list(template.get("features", []))

    return (
        AUTO_HEADER
        + f"\\documentclass{{{class_name}}}\n\n"
        + "\\UseTemplateSet{\n"
        + f"  layout = {layout},\n"
        + f"  globalfonts = {{{globalfonts}}},\n"
        + f"  fonts = {{{fonts}}},\n"
        + f"  features = {{{features}}}\n"
        + "}\n\n"
        + "\\input{generated-fonts.tex}\n\n"
        + f"\\title{{{title}}}\n"
        + (f"\\subtitle{{{subtitle}}}\n" if subtitle else "")
        + f"\\author{{{author}}}\n"
        + "\\date{\\today}\n\n"
        + "\\begin{document}\n"
        + "\\maketitle\n\n"
        + "\\input{generated-content.tex}\n\n"
        + "\\end{document}\n"
    )


def _generate_fonts(data: dict[str, Any], output_dir: Path) -> str:
    chunks = [AUTO_HEADER, "\n"]
    registry = load_registry(root=repo_root())
    for kind, config in data.get("fonts", {}).get("scripts", {}).items():
        if not isinstance(config, dict):
            continue
        pascal = pascal_case(kind)
        family = str(config.get("main", "")).strip()
        tex_script = str(config.get("tex_script", "")).strip()
        font_target, path_option, file_check = _resolve_font_target(kind, family, registry)
        font_options = []
        if path_option:
            font_options.append(f"Path={{{path_option}}}")
        if tex_script:
            font_options.append(f"Script={tex_script}")
        options = ""
        if font_options:
            options = "[\n  " + ",\n  ".join(font_options) + "\n]"
        if file_check:
            chunks.append(f"\\IfFileExists{{{file_check}}}{{%\n")
        else:
            chunks.append(f"\\IfFontExistsTF{{{family}}}{{%\n")
        chunks.append(f"  \\newfontfamily\\IMPEFont{pascal}{{{font_target}}}{options}\n")
        chunks.append("}{%\n")
        chunks.append(f"  \\PackageWarning{{impe}}{{Font `{family}` not found; using current family for {pascal}}}%\n")
        chunks.append(f"  \\newcommand{{\\IMPEFont{pascal}}}{{\\rmfamily}}%\n")
        chunks.append("}\n\n")
        chunks.append(f"\\newcommand{{\\IMPE{pascal}}}[1]{{{{\\IMPEFont{pascal} #1}}}}\n\n")
        chunks.append(f"\\newenvironment{{IMPE{pascal}Block}}\n")
        chunks.append(f"  {{\\par\\begingroup\\IMPEFont{pascal}}}\n")
        chunks.append("  {\\par\\endgroup}\n\n")
    return "".join(chunks)


def _resolve_font_target(
    kind: str,
    family: str,
    registry: dict[str, list[dict[str, Any]]],
) -> tuple[str, str, str]:
    root = repo_root()
    for entry in registry.get(kind, []):
        if str(entry.get("family", "")).lower() != family.lower():
            continue
        raw_path = str(entry.get("path", "")).strip()
        if not raw_path:
            continue
        path = (root / raw_path).resolve()
        if not path.exists() or not path.is_file():
            continue
        directory = str(path.parent).replace("\\", "/")
        filename = path.name
        return filename, directory + "/", str(path).replace("\\", "/")
    return family, "", ""


def _generate_content(data: dict[str, Any]) -> str:
    chunks = [AUTO_HEADER, "\n"]
    for block in data.get("content", []):
        block_type = block.get("type")
        if block_type == "text":
            chunks.append(escape_latex(str(block.get("value", ""))).rstrip() + "\n\n")
        elif block_type == "raw_tex":
            chunks.append(str(block.get("value", "")).rstrip() + "\n\n")
        elif block_type == "font_block":
            pascal = pascal_case(str(block.get("kind", "")))
            value = escape_latex(str(block.get("value", ""))).rstrip()
            chunks.append(f"\\begin{{IMPE{pascal}Block}}\n{value}\n\\end{{IMPE{pascal}Block}}\n\n")
        elif block_type == "paragraph":
            chunks.append(_generate_paragraph(block) + "\n\n")
    return "".join(chunks)


def _generate_paragraph(block: dict[str, Any]) -> str:
    parts: list[str] = []
    for span in block.get("spans", []):
        span_type = span.get("type")
        value = str(span.get("value", ""))
        if span_type == "text":
            parts.append(escape_latex(value))
        elif span_type == "raw_tex":
            parts.append(value)
        elif span_type == "font_span":
            pascal = pascal_case(str(span.get("kind", "")))
            parts.append(f"\\IMPE{pascal}{{{escape_latex(value)}}}")
    return "".join(parts)


def escape_latex(value: str) -> str:
    return "".join(LATEX_SPECIALS.get(char, char) for char in value)


def pascal_case(value: str) -> str:
    pieces = re.split(r"[^0-9A-Za-z]+", value)
    return "".join(piece[:1].upper() + piece[1:] for piece in pieces if piece) or "Script"


def _tex_list(values: Any) -> str:
    if isinstance(values, str):
        values = [item.strip() for item in values.split(",") if item.strip()]
    if not isinstance(values, list):
        return ""
    return ",".join(_tex_atom(value) for value in values)


def _tex_atom(value: Any) -> str:
    return re.sub(r"[^0-9A-Za-z_:-]", "", str(value))


def _tex_identifier(value: Any, fallback: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z_:-]", "", str(value))
    return cleaned or fallback
