"""Default dependency registry."""

from __future__ import annotations

from .models import DependencySpec


DEFAULT_DEPENDENCIES = [
    DependencySpec(
        id="py.regex",
        display_name="regex",
        kind="python_module",
        level="recommended",
        feature="Unicode script detection",
        params={"import_name": "regex", "pip_name": "regex"},
        install_hint="Install with: pip install regex",
        docs_url="https://pypi.org/project/regex/",
    ),
    DependencySpec(
        id="py.yaml",
        display_name="PyYAML",
        kind="python_module",
        level="recommended",
        feature="YAML font/profile config",
        params={"import_name": "yaml", "pip_name": "PyYAML"},
        install_hint="Install with: pip install PyYAML",
        docs_url="https://pypi.org/project/PyYAML/",
    ),
    DependencySpec(
        id="py.platformdirs",
        display_name="platformdirs",
        kind="python_module",
        level="recommended",
        feature="user config/data path management",
        params={"import_name": "platformdirs", "pip_name": "platformdirs"},
        install_hint="Install with: pip install platformdirs",
        docs_url="https://pypi.org/project/platformdirs/",
    ),
    DependencySpec(
        id="exe.lualatex",
        display_name="LuaLaTeX",
        kind="executable",
        level="recommended",
        feature="PDF build",
        params={"command": "lualatex"},
        install_hint="Install TeX Live or MiKTeX. IMPE uses LuaLaTeX as the preferred engine.",
    ),
    DependencySpec(
        id="exe.latexmk",
        display_name="latexmk",
        kind="executable",
        level="optional",
        feature="robust multi-pass LaTeX build",
        params={"command": "latexmk"},
        install_hint="Install latexmk through TeX Live or MiKTeX.",
    ),
    DependencySpec(
        id="exe.biber",
        display_name="biber",
        kind="executable",
        level="optional",
        feature="bibliography support",
        params={"command": "biber"},
        install_hint="Install biber through TeX Live or MiKTeX.",
    ),
    DependencySpec(
        id="exe.git",
        display_name="Git",
        kind="executable",
        level="optional",
        feature="project/version integration",
        params={"command": "git"},
        install_hint="Install Git for Windows or the system Git package.",
    ),
    DependencySpec(
        id="font.noto_serif_devanagari",
        display_name="Noto Serif Devanagari",
        kind="font",
        level="recommended",
        feature="Devanagari preview/output",
        params={"family": "Noto Serif Devanagari"},
        install_hint="Install Noto Serif Devanagari or configure another Devanagari font.",
    ),
    DependencySpec(
        id="font.noto_sans_devanagari",
        display_name="Noto Sans Devanagari",
        kind="font",
        level="optional",
        feature="Devanagari sans fallback",
        params={"family": "Noto Sans Devanagari"},
        install_hint="Install Noto Sans Devanagari or configure another Devanagari sans font.",
    ),
    DependencySpec(
        id="font.noto_serif_tibetan",
        display_name="Noto Serif Tibetan",
        kind="font",
        level="recommended",
        feature="Tibetan preview/output",
        params={"family": "Noto Serif Tibetan"},
        install_hint="Install Noto Serif Tibetan or configure another Tibetan font.",
    ),
    DependencySpec(
        id="font.noto_sans_tibetan",
        display_name="Noto Sans Tibetan",
        kind="font",
        level="optional",
        feature="Tibetan sans fallback",
        params={"family": "Noto Sans Tibetan"},
        install_hint="Install Noto Sans Tibetan or configure another Tibetan sans font.",
    ),
    DependencySpec(
        id="font.gentium_plus",
        display_name="Gentium Plus",
        kind="font",
        level="recommended",
        feature="Greek/Latin scholarly text",
        params={"family": "Gentium Plus"},
        install_hint="Install Gentium Plus or configure another scholarly Greek/Latin font.",
    ),
    DependencySpec(
        id="font.david_libre",
        display_name="David Libre",
        kind="font",
        level="recommended",
        feature="Hebrew preview/output",
        params={"family": "David Libre"},
        install_hint="Install David Libre or configure another Hebrew font.",
    ),
    DependencySpec(
        id="font.noto_sans_hebrew",
        display_name="Noto Sans Hebrew",
        kind="font",
        level="optional",
        feature="Hebrew sans fallback",
        params={"family": "Noto Sans Hebrew"},
        install_hint="Install Noto Sans Hebrew or configure another Hebrew sans font.",
    ),
    DependencySpec(
        id="font.noto_sans_arabic",
        display_name="Noto Sans Arabic",
        kind="font",
        level="optional",
        feature="Arabic preview/output",
        params={"family": "Noto Sans Arabic"},
        install_hint="Install Noto Sans Arabic or configure another Arabic font.",
    ),
]

